# 测试环境
ruoyi:
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: ${FILE_PATH}
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: ${TOKEN_KEY}
  # 令牌有效期（默认一天1440分钟）
  expireTime: 1440
spring:
  datasource:
    druid:
      # 主库数据源
      master:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
  # redis 配置
  redis:
    # 地址
    host: ${REDIS_HOST}
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: ${REDIS_PASSWORD}
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  elasticsearch:
    rest:
      uris: ${ES_URIS}
      connection-timeout: 10000ms