# 本地开发环境
ruoyi:
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/ruoyi/uploadPath/

token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 3000
spring:
  datasource:
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://113.44.157.104:23306/lvguan_platform?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: lvguan_platform
        password: fStcMNwNxwnYdEHK
#      master:
#        url: jdbc:mysql://localhost:3306/lvguan?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#        username: root
#        password: '0307'
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
  # redis 配置
  redis:
    # 地址
    host: 47.105.32.48
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 1
    # 密码
    password: W1dbhlad
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  elasticsearch:
    rest:
      uris: 113.44.157.104:9200
      connection-timeout: 10000ms